### ISSUE TITLE
Meta-issue: IDE improvements 

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty-feature-requests#42]
Testing Infrastructure:
----------------------
- [x] Test that go-to-definition, renaming, completion, … work @nicolasstucki 
  - WIP PR: https://github.com/lampepfl/dotty/pull/3766
  - May be handled by making a LSP client for testing based on [LSP4J](https://github.com/eclipse/lsp4j)
  - would be interesting to look at how other LSP servers deal with this.
- [ ] Integration tests with VSCode

Proper build integration:
----------------------
- [ ] Fetch documentation for external projects (not needed if we have TASTY, but that's not the case for Java dependencies at least), take inspiration from what metals does for this
- [ ] sbt server support (blocked by #3091)
- [ ] Handle outdated symbols (e.g. load symbol from TASTY from some classfile, then the classfile gets updated, the compiler doesn’t know the symbol is outdated)
- [ ] Handle project that don't compile: #3114. There are multiple ways we could handle this:
  - [x] If a name cannot be resolved, use heuristics to find corresponding source and load it in the typechecker. Need to implement a [SourcefileLoader](https://github.com/lampepfl/dotty/blob/dc52e6f970354bdb9f57f002952385572a59a667/compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala#L343)
  - [ ] When compiling multiple files and errors are found in one of them, the compilation process halts, consider finishing compilation for compilation units without errors (would also speed up incremental compilation in practice)
  - [ ] Generate TASTY files even when errors are present, for the sole benefit of the IDE ?

Features:
----------------------
- [x] Handle imports (currently, nothing happens when hovering over them)
- [ ] Support mixed Java/Scala projects, right now nothing happens when a .java file is opened. This probably means integrating with the [Java Language Server](https://github.com/eclipse/eclipse.jdt.ls).
- [x] Better completion. Require recreating Context in current scope, maybe by subclassing Typer
- [x] Documentation support @Duhemm 
  - Add a documentation section to TASTY
  - Use the dottydoc phases to “cook” the comments
- [ ] Debugging support @smarter
  - [ ] Basic support based on https://github.com/Microsoft/java-debug ([WIP branch](https://github.com/dotty-staging/dotty/commits/debug-server))
  - [ ] Support for evaluating Scala Expression (also present in the [WIP branch](https://github.com/dotty-staging/dotty/commits/debug-server))
 - [x] Worksheets
- [ ] Auto-import (Olaf has interesting ideas on how to achieve this)
- [ ] Prefix elision when displaying types (e.g., display `A[B]` instead of `foo.A[bar.B]` if `A` and `B` are in scope)

More Dotty LSP clients, so far:
----------------------
- vscode: https://github.com/lampepfl/dotty/tree/master/vscode-dotty
- emacs: https://github.com/smarter/emacs-lsp-dotty (WIP)
- IntelliJ: https://github.com/gtache/intellij-lsp (WIP)
- Atom: https://github.com/laughedelic/atom-ide-scala (WIP)

See http://langserver.org/ for a list of IDEs with LSP plugins that could be made to work with the Dotty Language Server.
